trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install dependencies'
- script: |
    npm run cy:run
  displayName: 'Run tests'
- script: |
    npm run cy:report
  displayName: 'Generate reports'
