version: '3.1'

volumes:
    jenkins-data:

services:

  jenkins:
    image: jenkinsci/blueocean
    restart: always
    ports:
      - 9191:8080
      - 50000:50000
    tty: true
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock